### ISSUE TITLE
use richardson extrapolation?

### ISSUE THREAD

**Issue by stevengj** [JuliaDiff/FiniteDifferences.jl#107]
I wonder if it would be useful to add a method using [Richardson.jl](https://github.com/JuliaMath/Richardson.jl), which can automatically [extrapolate low-order finite differences to high-order accuracy](https://github.com/JuliaMath/Richardson.jl#numerical-derivatives).   Another nice thing about Richardson extrapolation is that it automatically determines an appropriate step size — you just give it a relatively large initial guess, and it extrapolates downward, stopping automatically when cancellation errors take over.

**Comment by oxinabox** [comment]
@wesselb can you comment on this?

Also link to the PDF where all the current math is explained.

**Comment by wesselb** [comment]
That's very interesting. @stevengj, if I understand correctly, both Richardson extrapolation and direct construction of higher-order finite differences account for a number of terms of the Taylor expansion of the function. Contrary to the direct construction, Richardson extrapolation proceeds iteratively starting from a low-order method, and has a way of automatically detecting convergence. Could you comment on the convergence criterion? Does Richardson extrapolation tend to be robust, even when the initial guess for the step size is bad?

I can imagine a combination of both packages for robust, high-precision derivatives: start with a moderate-order (?) finite difference method with an automatically determined (hopefully good) step size, and then iterate with Richardson extrapolation to further refine the estimate.

Moreover, combining the ideas from both approaches (a geometrically converging sequence of step sizes and automatic balancing of truncation and round-off error), we could consider "geometric grids" like this:

```julia
julia> method = FiniteDifferences.Nonstandard(vcat(-(3 .^ [3, 2, 1]), 3 .^ [0, 1, 2, 3]), 1)

julia> fdm(method, sin, 1) - cos(1)
-1.3322676295501878e-15
```

What are your thoughts?

**Comment by stevengj** [comment]
> Does Richardson extrapolation tend to be robust, even when the initial guess for the step size is bad?

It's certainly much more robust than finite differences with a fixed step size.  The initial guess just needs to be large enough not to suffer catastrophic cancellation, but not so large that increasing the polynomial order does nothing for the fit.

For example, for differentiating `sin(x)` at `x=1` by extrapolating a first-order forward difference, it gets the correct answer to about 13 digits for initial step sizes `h` between about `h=0.01` and `h=6`, and gets 7 decimal places down to about `h=1e-8`.

Since it also returns an error estimate, you could in principle make it even more robust — if the error estimate is too large, you could redo the calculation with a larger or smaller step size (e.g. by a factor of 100), at the expense of more function evaluations.

> start with a moderate-order (?) finite difference method

Normally you would start Richardson extrapolation with a 1st or 2nd-order method.

**Comment by stevengj** [comment]
> Could you comment on the convergence criterion?

It's pretty straightforward: keep shrinking the step until the error estimate meets the tolerance or stops decreasing.   The main trick, however, it is that it considers the polynomial extrapolations from *all* possible subsequences ending at the current point.

In particular, suppose your initial step-size is h₀ and you contract by a factor `c` (typically 0.5) at each step.  On the `5`-th step, you will have evaluated your derivative rule at `h ∈ (h₀, ch₀, c²h₀, c³h₀, c⁴h₀)`.   It then does polynomial extrapolation using *each* of the subsequencess `(h₀, ch₀, c²h₀, c³h₀, c⁴h₀)`, `(ch₀, c²h₀, c³h₀, c⁴h₀)`, `(c²h₀, c³h₀, c⁴h₀)`, `(c³h₀, c⁴h₀)`  (The Neville tableau gives an efficient way to do this.)  For each subsequence, it estimates the error by comparing the result to what you would obtain by omitting the *last* term in the subseqence [e.g. it compares extrapolation from `(ch₀, c²h₀, c³h₀, c⁴h₀)` to extrapolation from `(ch₀, c²h₀, c³h₀)`].   Then, we choose the extrapolation with the minimum estimated error.

We stop when this minimum estimated error meets the requested tolerance, or when it increases by > factor of 2 compared to the previous iteration's minimum error (which is taken as a sign that convergence is failing, probably due to floating-point limitations).

**Comment by wesselb** [comment]
Thank you for your detailed answers. That all makes sense. Using extrapolations from all possible subsequences is clever. This certainly sounds promising!

To support the use of Richardson.jl to compute derivatives by extrapolating a finite difference, perhaps we could enable FiniteDifferences.jl to return the guessed step size and a function that computes the derivative as a function of the step size. Right now, `fdm` does not expose these two components: it just directly estimates the derivative. The guessed step size can then be used as a starting point for Richardson extrapolation. Moreover, we could add a function, e.g. `extrapolate_fdm`, that takes in a finite difference method and then extrapolates it with `extrapolate`. How would something like this sound?

**Comment by stevengj** [comment]
Yes, that sounds reasonable.

**Comment by stevengj** [comment]
Although the way you "guess" a step size might be totally different with Richardson extrapolation — you will coud want to use much larger step sizes to increase robustness to floating-point cancellation, since the extrapolation process will deal with the truncation process from larger steps.

**Comment by wesselb** [comment]
> Although the way you "guess" a step size might be totally different with Richardson extrapolation — you will could want to use much larger step sizes to increase robustness to floating-point cancellation, since the extrapolation process will deal with the truncation process from larger steps.

That's true. One ad hoc solution would be to multiply the guessed step size for a simple forward difference by a factor of 10 or 100 and use that as the starting point for Richardson extrapolation. Alternatively, we could modify the procedure to compute the step size to be more conservative, so that it will come out larger.

> How do you guess a step size anyway? It doesn't seem like this should be possible without some strong assumptions about the scaling of the function arguments.

To summarise, the step size is computed by [balancing the truncation error and round-off errors](https://github.com/JuliaDiff/FiniteDifferences.jl/blob/master/src/methods.jl#L263). For a single forward difference, this requires a bound on the magnitude of the second derivative, which the method estimates with another finite difference and forms the "adaptive" part of the step size computation. I'd be happy to provide more details if you'd like to.
