### ISSUE TITLE
High order, high adapt test failed in nightly

### ISSUE THREAD

**Issue by mzgubic** [JuliaDiff/FiniteDifferences.jl#113]
https://travis-ci.org/github/JuliaDiff/FiniteDifferences.jl/jobs/743817980

**Comment by oxinabox** [comment]
Can we check the coeffs and grid?
Last time this happened it was because `\` got less accurate.

**Comment by mzgubic** [comment]
I can't reproduce the error on my local machine, and the nightly [seems to have passed today](https://travis-ci.org/github/JuliaDiff/FiniteDifferences.jl/builds). Weird. Should we close this?

**Comment by oxinabox** [comment]
Yeah, maybe it was cosmic rays
