### ISSUE TITLE
Accuracy is a bit brittle

### ISSUE THREAD

**Issue by giordano** [JuliaDiff/FiniteDifferences.jl#124]
The [README](https://github.com/JuliaDiff/FiniteDifferences.jl/blob/673d6fa25c6eb7ac8a97d3e4ea8ca250219d3f88/README.md) of this package convinced me to [use `FiniteDifferences` instead of `Calculus` in `Measurements`](https://github.com/JuliaPhysics/Measurements.jl/pull/82) for cases where I need a numerical derivative (for functions without known derivative or automatic differentiation isn't possible, e.g. calling into C libraries).  However I found that accuracy of `FiniteDifferences` is quite brittle (sometimes strongly depends on the number of points with big even/odd jumps, see example below) and I need to use a largish number of grid points to achieve the same accuracy I have with `Calculus`, which in comparison is also much faster (and makes me question the change of the backend).  For example, the derivative of `cosc` in 0 is -(pi^2)/3, with Julia v1.5.3 I get:
```julia
julia> using Calculus, FiniteDifferences, BenchmarkTools

julia> -(pi ^ 2) / 3
-3.289868133696453

julia> (p -> FiniteDifferences.central_fdm(p, 1)(cosc, 0)).(2:10)
9-element Array{Float64,1}:
 -3.2575126788312536 # 2
  0.0                # 3
 -3.2894144933275746 # 4
 -3.9730287078618036 # 5 
 -3.289860720421136  # 6
 -3.2898376423854927 # 7
 -3.2898681297554884 # 8
 -3.289868469475128  # 9
 -3.2898681348743732 # 10

julia> Calculus.derivative(cosc, 0) 
-3.2898678494407765
```
To achieve an accuracy of the same order as `Calculus` I need 8 grid points, and this is the performance comparison:
```julia
julia> @btime FiniteDifferences.central_fdm(8, 1)($cosc, 0)
  2.340 μs (25 allocations: 992 bytes)
-3.2898681297554884

julia> @btime Calculus.derivative($cosc, 0)
  60.591 ns (0 allocations: 0 bytes)
-3.2898678494407765
```

Is this behaviour really expected?

**Comment by nickrobinson251** [comment]
Doesn't sound expected to me. Would you mind trying with FiniteDifferences v0.10, to see if this changed between versions?

cc @wesselb

**Comment by wesselb** [comment]
Ouch, this looks very bad. A preliminary investigation shows that the estimated step size is _way_ too small. I'm suspecting that the issue is that both the argument is `0.0` and `cosc(0.0) = 0.0`. Fixing the latter appears to resolve the issue:

```julia
julia> FiniteDifferences.central_fdm(4, 1)(x -> cosc(x) + 1, 0) .+ (pi ^ 2) / 3
4.785150053976395e-11

julia> Calculus.derivative(cosc, 0).+ (pi ^ 2) / 3
2.8425567633050264e-7
```

I'll further look into this.

Performance of the package is definitely something that at some point needs to be addressed.

**Comment by wesselb** [comment]
I should also say that the package since recently supports Richardson extrapolation with Richardson.jl, which is an alternative that does not break in this case:

```julia
julia> @btime FiniteDifferences.extrapolate_fdm(FiniteDifferences.central_fdm(2, 1, adapt=0), f, 0.0)[1] + (pi ^ 2) / 3
  1.898 μs (29 allocations: 1.44 KiB)
-3.455082886461014e-9
```

**Comment by giordano** [comment]
I confirm #125 addresses my complaints, thanks @wesselb!!
