### ISSUE TITLE
Should `rand_tangent(2:3)` return `DoesNotExist()`?

### ISSUE THREAD

**Issue by mzgubic** [JuliaDiff/FiniteDifferences.jl#149]
I can't think of any use-case where the current
```julia
julia> ChainRulesTestUtils.rand_tangent(2:3)
Composite{UnitRange{Int64}}(start = ChainRulesCore.DoesNotExist(), stop = ChainRulesCore.DoesNotExist())
```
would be the better option, can anyone else?

There are potentially other indices that could be updated, such as `CartesianIndex` and `(:)`.

**Comment by willtebbutt** [comment]
Coming back to this: I feel strongly that patching this by making this a `DoesNotExist` is a bad idea, and that we ought to make `to_vec` work properly for subtypes of `AbstractArray`.

**Comment by mzgubic** [comment]
Is it possible to write `to_vec` for a `UnitRange`/`StepRange`/`StepRangeLen`? I mean, it's easy to turn it into a vector, but once you perturb the vector it is no longer possible to construct a range from it, right?

In other words these various ranges seem to be outside of the domain of the `to_vec` function. Perhaps the fallback `to_vec` methods for `AbstractArray/Vector` should instead be `StridedArray/Vector`?

**Comment by willtebbutt** [comment]
> Is it possible to write to_vec for a UnitRange/StepRange/StepRangeLen? I mean, it's easy to turn it into a vector, but once you perturb the vector it is no longer possible to construct a range from it, right?

So this is another example of the "is it an array, or is it a struct?" question. In this case I think it's clear cut that they ought to be treated as structs. If you take that view, there's really no problem -- they're just structs and we utilise the recursive definition of `to_vec` like we would for any other struct.

> In other words these various ranges seem to be outside of the domain of the to_vec function. Perhaps the fallback to_vec methods for AbstractArray/Vector should instead be StridedArray/Vector?

I think that we should try to implement these tighter typing constraints anyway because, as we can see in this example, `to_vec(::AbstractArray)` doesn't work.

**Comment by oxinabox** [comment]
`rand_tangent(2:3)`  *should* return `DoesNotExist()`.
particularly since `rand_tangent(1)` returns that.
We treat integers as non-pertubable.
thus `AbstractArray{<:Interger}` should also be non-perturable.

**Comment by willtebbutt** [comment]
Agreed -- either that or a `Composite` with `DoesNotExist()`s in.

**Comment by mzgubic** [comment]
> Agreed -- either that or a `Composite` with `DoesNotExist()`s in.

This is what we have now btw (after https://github.com/JuliaDiff/FiniteDifferences.jl/pulls)
