### ISSUE TITLE
`rand_tangent(::Colon)` should return `DoesNotExist()`

### ISSUE THREAD

**Issue by mzgubic** [JuliaDiff/FiniteDifferences.jl#153]
first mentioned in https://github.com/JuliaDiff/ChainRules.jl/pull/396#discussion_r609619038

**Comment by willtebbutt** [comment]
Is this true? It's a struct, and it doesn't have any fields, so `NO_FIELDS` seems appropriate, this is what [this rule](https://github.com/JuliaDiff/FiniteDifferences.jl/blob/c31952549df3607c4809d141c533d83d0015e23a/src/rand_tangent.jl#L26) does.

However, `NO_FIELDS` is currently equal to `Zero`.

It seems we have a contradiction. @oxinabox ?

**Comment by willtebbutt** [comment]
> I do agree that DoesNotExist makes sense though.

In light of reviewing https://github.com/JuliaDiff/ChainRulesCore.jl/issues/175, I retract this. An empty `Composite` makes more sense to me.
