### ISSUE TITLE
grad wraps result in a tuple

### ISSUE THREAD

**Issue by tpapp** [JuliaDiff/FiniteDifferences.jl#219]
Eg
```julia
julia> f(x) = sum(abs2, x)
f (generic function with 1 method)

julia> FiniteDifferences.grad(FiniteDifferences.central_fdm(5, 1), f, ones(3))
([1.9999999999999902, 1.9999999999999902, 1.9999999999999902],)
```

This is not mentioned by a docstring, even though the examples use `[1]` to extract the gradient.

1. is there an inherent reason for doing this?
2. would it make sense to simply return the vector? (this is a breaking API change)
3. if not, the docstring could mention the reason

**Comment by oxinabox** [comment]
@wesselb or @willtebbutt may remember why.
I never use `grad` only `vjp` and co,
so that part of interface may be a bit stale, and in general I think its desirable at some point (maybe this is already done) to expose that interface consistently via AbstractDifferentiation.jl

**Comment by tpapp** [comment]
> expose that interface consistently

Yep, doing that in https://github.com/tpapp/LogDensityProblemsAD.jl/pull/16, just curious about the interface of this package.

**Comment by willtebbutt** [comment]
This is done for consistency with the multi-argument version. i.e. `grad` will always return a `Tuple`, with as many elements as the number of arguments.

**Comment by tpapp** [comment]
Makes perfect sense, thanks! I made a minor doc PR that clarifies this.
