### ISSUE TITLE
Comparing equivalent functions with unequal finite difference results?

### ISSUE THREAD

**Issue by jessebett** [JuliaDiff/FiniteDifferences.jl#33]
I am a bit confused by a difference between two functions I've written to be equivalent. I am trying to make a function more general by summing over get index operations instead of hard coding the number of terms. I produced what I thought are equivalent functions, and when they are evaluated they are equivalent. However, when I finite difference them the results are slightly different. Is this a numerical error?

```
method = central_fdm(10,3)
expansion1 = ϵ -> f(x + ϵ.^1 * v[1]/factorial(1) + ϵ.^2 * v[2] / factorial(2) + ϵ.^3 * v[3] / factorial(3))
expansion2 = ϵ -> f(x + sum(ϵ.^i * v[i] / factorial(i) for i in 1:3))
f=sin
x= 2.
v = (1.,1.,1.)

method(expansion1,0.)
method(expansion2,0.)
```

Which produces:
```
julia> method(expansion1,0.)
-2.727892280564907

julia> method(expansion2,0.)
-2.7278922805817447
```

Where is this difference coming from?

**Comment by oxinabox** [comment]
Seems like a numerical round off issue to me.
Notice how the difference gets smaller when you use `BigFloats`
``
julia> method(expansion1,big"0.")
-2.72789227968587038443263903045410791221359958425212827040549993117581567989842

julia> method(expansion2,big"0.")
-2.727892279685870384432639030454107912213599584252128270405499931175816077618578
```

Probably worth looking at higher precision sum operations (like Kahan summation)
and `muladd`.

**Comment by jessebett** [comment]
Thanks @oxinabox I should have tested like this.
