### ISSUE TITLE
Users of FDM can update to FiniteDifferences

### ISSUE THREAD

**Issue by nickrobinson251** [JuliaDiff/FiniteDifferences.jl#37]
We should add the following advice to the README?

- We renamed the package for discoverability 
- Turns out to rename it we had to actually register it as a new package (with a new UUID)...
- This means the old FDM URL redirects here. Packages dependening of FDM will not be affected. But all future updates will be to FiniteDifferences (not FDM).
- As far as i can tell, functionally this new package has no breaking changes from the last FDM release (counting #34 as a bug-fix)
- User can safely update their Project.toml files from
```julia
[deps]
FDM = "e25cca7e-83ef-51fa-be6c-dfe2a3123128"
...

[compat]
FDM = "0.6"
```
to 
```julia
[deps]
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
...

[compat]
FiniteDifferences = "0.7"
```

**Comment by nickrobinson251** [comment]
need the package to be registered first https://github.com/JuliaRegistries/General/pull/2535

**Comment by nickrobinson251** [comment]
Added a note to the README (#38). It just links to this issue which has all the info at the top ^^^

Let's leave the issue open for now - so people can find it and in case people have questions on updating - but I don't think anything else needs doing here :)

**Comment by oxinabox** [comment]
I think we can now close this
