### ISSUE TITLE
complex derivatives

### ISSUE THREAD

**Issue by Roger-luo** [JuliaDiff/FiniteDifferences.jl#50]
there are two different kind of derivatives for complex valued function, one the df/dz, the other is the df/d conj(z). It'd be nice to support both.

**Comment by willtebbutt** [comment]
@Roger-luo is this issue resolved from your perspective?

**Comment by Roger-luo** [comment]
I'm not sure, how do you calculate the complex derivative currently? I haven't been following recent updates.

**Comment by willtebbutt** [comment]
```julia
julia> FiniteDifferences.grad(central_fdm(5, 1), abs2 ∘ cos, 1.0 + 1.0im)
(-0.9092974268258326 + 3.6268604078472806im,)
```

**Comment by Roger-luo** [comment]
yeah I think I was thinking about using two interface (one for df/dz the other for df/dconj(z), this is good on my side now. I'll post other issues if I find anything, thanks!
