### ISSUE TITLE
gradient of maximum is not correct

### ISSUE THREAD

**Issue by Roger-luo** [JuliaDiff/FiniteDifferences.jl#53]
This is causing test broken in Zygote

```jl
fdm = central_fdm(5, 3)
Random.seed!(0);
M = rand(2, 3);
tmp = similar(M);

fdm(0.0) do ϵ
           tmp .= M
           tmp[1] += ϵ
           return maximum(tmp)
end
43.35451497451203
```

**Comment by willtebbutt** [comment]
Hmm. Well the gradient of `maximum` jumps around whenever you're near a point where the location of the maximum element changes (i.e. from `0` -> `1` and `1` -> `0` at the new max / old max locations respectively). So, for example,
```julia
julia> x = [1.0, 0.0];

julia> tmp = similar(x);

julia> fdm(0.0) do ϵ
           tmp .= x
           tmp[1] += ϵ
           return maximum(tmp)
       end
0.9999999999999811

julia> fdm(0.0) do ϵ
           tmp .= x
           tmp[2] += ϵ
           return maximum(tmp)
       end
6.5051510603102805e-15
```
This also gives well-behaved 3rd derivatives with `central_fdm(5, 3)`. Conversely, if the values in `x` are too close together we get incorrect results:
```julia
julia> fdm = central_fdm(5, 1);
julia> x = [1e-6, 0.0];
julia> tmp = similar(x);

julia> fdm(0.0) do ϵ
           tmp .= x
           tmp[1] += ϵ
           return maximum(tmp)
       end
0.6175432605559212

julia> fdm(0.0) do ϵ
           tmp .= x
           tmp[2] += ϵ
           return maximum(tmp)
       end
0.3824567394426718
```
So I guess the question is whether you've happened to get some very close-together elements in `M`?

Also, are you intentionally taking the 3rd derivative? I wasn't aware that Zygote was doing anything nested at the minute.

**Comment by Roger-luo** [comment]
> So I guess the question is whether you've happened to get some very close-together elements in M?

yes, but I can't workaround this, since it is just `rand`.

> Also, are you intentionally taking the 3rd derivative? I wasn't aware that Zygote was doing anything nested at the minute.

no I'm just trying to fix the tests in Zygote (I've marked it broken for now)

**Comment by willtebbutt** [comment]
> yes, but I can't workaround this, since it is just rand.

Okay. Could you provide the exact numbers that you have for `M`? I'm not able to reproduce the error (I correctly get zero), but that might be because we're generating different values for `M`.

> no I'm just trying to fix the tests in Zygote (I've marked it broken for now)

Okay, you probably want `central_fdm(5, 1)` then. This constructs a 5th-order estimate of the 1st derivative.

**Comment by Roger-luo** [comment]
I have it in the example as `M = rand(2, 3)` (`Random.seed!(0)`) or you could just try to run the Zygote test: https://github.com/FluxML/Zygote.jl/pull/235/files#diff-d0759c4bbbe4bfe282ccf2f6fc082320R204

**Comment by willtebbutt** [comment]
Yup, I tried with your seed and wasn't able to reproduce locally. Possible I'm running a different Julia version to you or something, and consequently getting different numbers. For the sake of diagnosing the issue it would be helpful to know precisely which numbers are causing the issue.

**Comment by Roger-luo** [comment]
ok, this is the `M` I got

```jl
julia> M
2×3 Array{Float64,2}:
 0.823648  0.164566  0.27888 
 0.910357  0.177329  0.203477
```

**Comment by willtebbutt** [comment]
Okay, I am using the same numbers and am unable to reproduce. Am running the Zygote tests locally to see if I can reproduce.

**Comment by willtebbutt** [comment]
All of the `maximum`-related tests pass locally for me @Roger-luo . Not sure what's going on :S

**Comment by Roger-luo** [comment]
that's strange... this is my versioninfo:

```jl
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.0.0)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

what's yours?

**Comment by willtebbutt** [comment]
Hmmmm.

```julia
Julia Version 1.3.0-rc2.0
Commit a04936e3e0 (2019-09-12 19:49 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)
Environment:
  JULIA_NUM_THREADS = 1
  JULIA_EDITOR = subl
```
Would you mind trying out this version? Also, I'm running `FiniteDifferences.jl` on master.

**Comment by Roger-luo** [comment]
This is strange, I tried it on other versions e.g 1.3-rc4, or the master branch, this is 0.0, but on 1.2 it is not...

can you reproduce this behaviour on 1.2 as well?

**Comment by Roger-luo** [comment]
I guess there is some bug in 1.2, but since 1.3 is out now I think I'll just close this and move on somehow.
