### ISSUE TITLE
Less accurate results on Julia 1.3.1 vs Julia 1.1.1

### ISSUE THREAD

**Issue by jtravs** [JuliaDiff/FiniteDifferences.jl#64]
If I run
```
FiniteDifferences.fdm(FiniteDifferences.central_fdm(9, 5), y->exp(y), 1.0, adapt=4)
```
on Julia 1.1.1 I get:
```
2.718281560120131
```
whereas on Julia 1.3.1 I get
```
2.7182639618941993
```
which is much less accurate (error of 1.8e-5 vs 2.7e-7).

This broke some tests of ours. Does anyone know why the accuracy is reduced?

Both on v0.9.2.

**Comment by jtravs** [comment]
I have also tested Julia 1.2 and Julia 1.4. The loss in precision occurs between Julia 1.2 and 1.3.1.
Note that this is not a feature of the ```exp``` function. For example
```
f(x) = @. 4x^3 + 3x^2 + 2x + 1
FiniteDifferences.fdm(FiniteDifferences.central_fdm(9, 3), f, 1.0, adapt=4)
```
gives ```23.999999999999137``` on Julia 1.2 (error of 8.6e-13) but ```24.00000000064826``` on Julia 1.4 (error of 6.482601122570486e-10).

I know finite differences are tricky and suffer numerical error, but it would be useful to at least understand where this has come from.

**Comment by oxinabox** [comment]
You'll need to take this up on [JuliaLang/julia](https://github.com/JuliaLang/julia/issues).
As the version of this package you use in 1.2 and 1.4 is the same.
So it must be an underlying change in the standard libraries (probably Base, but maybe LinearAlgebra?)

**Comment by jtravs** [comment]
Shall I open an issue there?

**Comment by oxinabox** [comment]
We could do.
Ideally we would narrow it down to a more minimal case.

One candidate is:
the change in behavour of: `C\x`

https://github.com/JuliaDiff/FiniteDifferences.jl/blob/74614e211fbffc84b976dbd836b33acf18b27e63/src/methods.jl#L163

Kristoffer Carlsson  points out that:

On 1.4:
```
julia> C \ x
9-element Array{Float64,1}:
  0.1666666666666667
 -1.5000000000000016
  4.333333333333361
 -4.833333333333374
  2.6462090141384603e-14
  4.833333333333272
 -4.333333333333288
  1.499999999999994
 -0.1666666666666662
```

and 1.2
```
julia> C \ x
9-element Array{Float64,1}:
  0.1666666666666643
 -1.5
  4.333333333333336
 -4.833333333333333
  0.0
  4.833333333333333
 -4.333333333333333
  1.5
 -0.16666666666666666
```

The 1.2 numbers are defintely cleaner.
But wether that is enough to aftect the algorith, I am not sure

**Comment by oxinabox** [comment]
As of #65 (should be available in release if you do `] up` in ~10 minutes)
this is now much more accurate both in julia 1.2 and 1.4, so all should be good now.

**Comment by jtravs** [comment]
This is great. Thank you!

However, it appears to me that only 0.9.2 is released (2nd Feb). When I try to upgrade this package it stays at 0.9.2.

**Comment by nickrobinson251** [comment]
@oxinabox looks like a version got skipped so the latest release hasn't gone out yet
https://github.com/JuliaRegistries/General/pull/12378

**Comment by oxinabox** [comment]
Now it has
