### ISSUE TITLE
ChainRules tests are failing on 0.9.4

### ISSUE THREAD

**Issue by oxinabox** [JuliaDiff/FiniteDifferences.jl#70]
e.g. https://travis-ci.org/github/JuliaDiff/ChainRules.jl/jobs/673580313

Looks like real differences, so I think something is still broken that wasn't fixed by #68 

@willtebbutt are you able to investigate by doing the whole 
`] dev ChainRules FiniteDifferences`
`] test ChainRules` 

thing?

**Comment by willtebbutt** [comment]
Yup. Will take a look in the morning.

**Comment by oxinabox** [comment]
thank you (feel free to leave it til tuesday if that is better for you)

**Comment by nickrobinson251** [comment]
resolved by https://github.com/JuliaDiff/FiniteDifferences.jl/pull/71
