### ISSUE TITLE
Revert last commit

### ISSUE THREAD

**Issue by willtebbutt** [JuliaDiff/FiniteDifferences.jl#77]
I stupidly bumped the patch version 🤦‍♂️  rather than minor version when merging #76 , as helpfully pointed out by @simeonschaub . I want to

1. revert to the previous commit
2. make another patch release correcting the mistake
3. make a minor release as originally intended.

Unfortunately, my googling + git skills aren't up to the task at the minute. Help (either hints about how to go about doing this, or in the form of a PR that does 1 and 2) would be much appreciated.

**Comment by nickrobinson251** [comment]
Thanks for catching this so early! Thanks, @simeonschaub in particular, for making the PRs :)

- https://github.com/JuliaDiff/FiniteDifferences.jl/releases/tag/v0.9.8
- https://github.com/JuliaRegistries/General/pull/13636
